---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=3600

- name: Ensure Apache is installed.
  apt: "name={{ item }} state=present"
  with_items: 
    - apache2

- name: Add apache vhosts configuration.
  template:
    src: vhosts.conf.j2
    dest: "/etc/apache2/sites-available/{{ host }}.conf"
    owner: root
    group: root
    mode: 0644
  notify: restart apache

- name: Add vhost symlink in sites-enabled.
  file:
    src: "/etc/apache2/sites-available/{{ host }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ host }}.conf"
    state: link
  notify: restart apache

- name: Remove default vhost in sites-enabled.
  file:
    path: "/etc/apache2/sites-enabled/000-default.conf"
    state: absent
  notify: restart apache

- name: Ensure Apache has selected state and enabled on boot.
  service:
    name: apache2
    state: started
    enabled: yes
