---
- name: Upgrade
  apt: upgrade=yes update_cache=yes cache_valid_time=360

- name: Ensure common packages are installed.
  apt: "name={{ item }} state=installed"
  with_items:
    - vim
    - aptitude