---
- name: Install Aptitude
  apt: name=aptitude update_cache=yes state=latest

- name: Upgrade
  apt: upgrade=yes update_cache=yes cache_valid_time=360

- name: Install Git
  apt: name=git update_cache=yes state=latest
