- name: Ensure directory exists
  file:
    path: "{{ laravel_path }}"
    state: directory

- name: Upload code
  synchronize:
    src: "../../../../laravel"
    dest: "{{ laravel_path }}"
    archive: yes
    checksum: yes
    rsync_path: "sudo rsync"
    rsync_opts:
      - "--exclude=.git*"