---
- name: Ensure MySQL Python libraries are installed.
  apt: "name=python-mysqldb state=installed"

- name: Ensure MySQL packages are installed.
  apt: "name={{ item }} state=installed"
  with_items:
    - mariadb-server
    - mariadb-client

- name: Ensure MySQL is started and enabled on boot.
  service: "name=mysql state=started enabled=yes"
  register: mysql_service_configuration

- name: Ensure MySQL databases are present.
  mysql_db:
    name: "{{ db_database }}"
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Ensure MySQL users are present.
  mysql_user:
    name: "{{ db_user }}"
    host: "%"
    password: "{{ db_password }}"
    priv: "*.*:ALL"
    state: present
    append_privs: no
    encrypted: no