- name: Ensure directory exists
  file:
    path: "{{ wp_path }}"
    state: directory

- name: Upload code
  synchronize:
    src: "../../../../wp/"
    dest: "{{ wp_path }}"
    archive: yes
    checksum: yes
    rsync_path: "sudo rsync"
    rsync_opts:
      - "--exclude=.git*"

- template:
    src: wp-config.php.j2
    dest: "{{ wp_path }}/wp-config.php"